# Generated by Django 2.2.6 on 2019-10-31 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.CharField(max_length=150)),
                ('descricao', models.CharField(max_length=500)),
            ],
        ),
    ]
