# Generated by Django 2.2.6 on 2019-10-31 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191031_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='email',
        ),
        migrations.AddField(
            model_name='items',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
    ]
