# Generated by Django 2.2.6 on 2019-10-31 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191031_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='short',
            field=models.CharField(default='Best offer', max_length=50),
            preserve_default=False,
        ),
    ]
