# Generated by Django 2.2.6 on 2019-11-01 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20191101_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrinho',
            old_name='auto_increment_id',
            new_name='id',
        ),
    ]
