# Generated by Django 2.2.6 on 2019-11-01 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_carrinho'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carrinho',
        ),
    ]
