# Generated by Django 2.2.6 on 2019-11-01 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_carrinho'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField(default=1)),
                ('unitValue', models.DecimalField(decimal_places=2, default=1, max_digits=11)),
                ('total', models.DecimalField(decimal_places=2, default=1, max_digits=11)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Items')),
            ],
        ),
    ]
