# Generated by Django 2.2.6 on 2019-11-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_carrinho'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='autor',
            field=models.CharField(default='ruioc', max_length=50),
            preserve_default=False,
        ),
    ]
