# Generated by Django 2.2.6 on 2019-11-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_carrinho_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='descricao',
            field=models.CharField(max_length=5000),
        ),
    ]
