# Generated by Django 2.2.6 on 2019-11-03 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20191103_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomenda',
            name='user',
            field=models.CharField(default='ruioc', max_length=50),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='encomenda',
            name='produtos',
        ),
        migrations.AddField(
            model_name='encomenda',
            name='produtos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Items'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='items',
            name='picture',
            field=models.ImageField(default='app/static/img/default_item.jpg', upload_to='app/static/img/item/-1592207708/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='app/static/img/default.jpg', upload_to='app/static/img/profile_pictures/-1592207708/'),
        ),
    ]
